[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python ingest.py"]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"