[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["python -m pip install --upgrade pip"]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"